name: Node.js CI

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build
        run: |
          echo "Building the project..."
          CI=false npm run build
          echo "Build completed"

      - name: Deploy with GitHub Pages
        uses: peaceiris/actions-gh-pages@v4 # Updated to v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build # Ensure this matches your build output directory
